--Bảng TAIKHOAN
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('alice@example.com', 'alice123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('bob@example.com', 'bobpass', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('charlie@example.com', 'charlie456', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('diana@example.com', 'diana789', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('eve@example.com', 'evepass', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('frank@example.com', 'frank123', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('grace@example.com', 'gracepwd', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('heidi@example.com', 'heidi456', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('ivan@example.com', 'ivan321', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('judy@example.com', 'judypass', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('karen@example.com', 'karenpass', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('leo@example.com', 'leo123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('mia@example.com', 'mia456', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('nick@example.com', 'nickpwd', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('olivia@example.com', 'oliviapass', 'Customer');

INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('employee1@park.com', 'empPass1', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('employee2@park.com', 'empPass2', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('employee3@park.com', 'empPass3', 'Employee', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('employee4@park.com', 'empPass4', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('employee5@park.com', 'empPass5', 'Employee');
COMMIT;

-- Bảng KHACHHANG
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Alice Nguyễn', TO_DATE('1995-04-10', 'YYYY-MM-DD'), 'Nữ', '0911000001', 'TK074');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Bob Trần', TO_DATE('1990-08-22', 'YYYY-MM-DD'), 'Nam', '0911000002', 'TK075');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Charlie Phạm', TO_DATE('1992-12-01', 'YYYY-MM-DD'), 'Nam', '0911000003', 'TK076');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Diana Lê', TO_DATE('1996-07-15', 'YYYY-MM-DD'), 'Nữ', '0911000004', 'TK077');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Eve Vũ', TO_DATE('1994-05-30', 'YYYY-MM-DD'), 'Nữ', '0911000005', 'TK078');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Frank Đặng', TO_DATE('1988-03-18', 'YYYY-MM-DD'), 'Nam', '0911000006', 'TK079');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Grace Hồ', TO_DATE('1993-11-11', 'YYYY-MM-DD'), 'Nữ', '0911000007', 'TK080');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Heidi Trịnh', TO_DATE('1991-09-09', 'YYYY-MM-DD'), 'Nữ', '0911000008', 'TK081');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Ivan Nguyễn', TO_DATE('1989-06-25', 'YYYY-MM-DD'), 'Nam', '0911000009', 'TK082');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Judy Mai', TO_DATE('1995-10-05', 'YYYY-MM-DD'), 'Nữ', '0911000010', 'TK083');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Karen Bùi', TO_DATE('1997-02-20', 'YYYY-MM-DD'), 'Nữ', '0911000011', 'TK084');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Leo Võ', TO_DATE('1992-03-30', 'YYYY-MM-DD'), 'Nam', '0911000012', 'TK085');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Mia Đỗ', TO_DATE('1996-01-19', 'YYYY-MM-DD'), 'Nữ', '0911000013', 'TK086');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Nick Lâm', TO_DATE('1990-12-07', 'YYYY-MM-DD'), 'Nam', '0911000014', 'TK087');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, GIOITINH, SDT, MATK) VALUES ('Olivia Phan', TO_DATE('1993-08-03', 'YYYY-MM-DD'), 'Nữ', '0911000015', 'TK088');

-- Bảng NHANVIEN
INSERT INTO NHANVIEN (MANV, HOTEN, NGSINH, GIOITINH, SDT, NGAYVL, CHUCVU, LUONG, MATK) VALUES ('NV001', 'Nguyễn Văn An', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'Nam', '0901000001', TO_DATE('2022-01-10', 'YYYY-MM-DD'), 'Quản lý', 15000000, 'TK089');
INSERT INTO NHANVIEN (MANV, HOTEN, NGSINH, GIOITINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK) VALUES ('NV002', 'Trần Thị Bình', TO_DATE('1993-08-20', 'YYYY-MM-DD'), 'Nữ', '0901000002', TO_DATE('2023-02-01', 'YYYY-MM-DD'), 'Nhân viên bán vé', 9000000, 'NV001', 'TK090');
INSERT INTO NHANVIEN (MANV, HOTEN, NGSINH, GIOITINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK) VALUES ('NV003', 'Lê Văn Cường', TO_DATE('1988-12-05', 'YYYY-MM-DD'), 'Nam', '0901000003', TO_DATE('2021-06-15', 'YYYY-MM-DD'), 'Nhân viên bảo trì', 9500000, 'NV001', 'TK091');
INSERT INTO NHANVIEN (MANV, HOTEN, NGSINH, GIOITINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK) VALUES ('NV004', 'Phạm Thị Duyên', TO_DATE('1995-10-10', 'YYYY-MM-DD'), 'Nữ', '0901000004', TO_DATE('2023-09-05', 'YYYY-MM-DD'), 'Nhân viên chăm sóc khách hàng', 8500000, 'NV001', 'TK092');
INSERT INTO NHANVIEN (MANV, HOTEN, NGSINH, GIOITINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK) VALUES ('NV005', 'Hoàng Văn Em', TO_DATE('1991-04-25', 'YYYY-MM-DD'), 'Nam', '0901000005', TO_DATE('2022-11-12', 'YYYY-MM-DD'), 'Nhân viên vận hành trò chơi', 9000000, 'NV001', 'TK093');

-- Bảng SUKIEN
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK001', 'Lễ hội mùa xuân', 'Giải trí', TO_DATE('2025-03-01', 'YYYY-MM-DD'), TO_DATE('2025-03-07', 'YYYY-MM-DD'), 'Sự kiện khai xuân với nhiều hoạt động truyền thống.', 'NV001');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK002', 'Ngày hội thiếu nhi', 'Gia đình', TO_DATE('2025-06-01', 'YYYY-MM-DD'), TO_DATE('2025-06-01', 'YYYY-MM-DD'), 'Chương trình dành cho trẻ em với trò chơi và quà tặng.', 'NV002');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK003', 'Tuần lễ ẩm thực', 'Ẩm thực', TO_DATE('2025-07-15', 'YYYY-MM-DD'), TO_DATE('2025-07-21', 'YYYY-MM-DD'), 'Giới thiệu các món ăn đặc sản ba miền.', 'NV003');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK004', 'Đêm nhạc DJ', 'Âm nhạc', TO_DATE('2025-05-10', 'YYYY-MM-DD'), TO_DATE('2025-05-10', 'YYYY-MM-DD'), 'Biểu diễn DJ sôi động tại sân khấu trung tâm.', 'NV004');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK005', 'Trò chơi dân gian', 'Giải trí', TO_DATE('2025-08-20', 'YYYY-MM-DD'), TO_DATE('2025-08-22', 'YYYY-MM-DD'), 'Khách tham quan được trải nghiệm trò chơi dân gian Việt Nam.', 'NV005');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK006', 'Ngày hội cosplay', 'Giải trí', TO_DATE('2025-09-05', 'YYYY-MM-DD'), TO_DATE('2025-09-05', 'YYYY-MM-DD'), 'Cuộc thi hóa trang theo nhân vật hoạt hình/anime.', 'NV002');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK007', 'Ngày hội khuyến mãi', 'Khuyến mãi', TO_DATE('2025-10-01', 'YYYY-MM-DD'), TO_DATE('2025-10-07', 'YYYY-MM-DD'), 'Giảm giá đặc biệt cho vé vào cửa và dịch vụ.', 'NV001');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK008', 'Tuần lễ Halloween', 'Giải trí', TO_DATE('2025-10-25', 'YYYY-MM-DD'), TO_DATE('2025-10-31', 'YYYY-MM-DD'), 'Trang trí kinh dị và các hoạt động hóa trang.', 'NV004');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK009', 'Săn trứng Phục Sinh', 'Gia đình', TO_DATE('2025-04-20', 'YYYY-MM-DD'), TO_DATE('2025-04-20', 'YYYY-MM-DD'), 'Trò chơi tìm trứng Phục Sinh cho trẻ em.', 'NV003');
INSERT INTO SUKIEN (MASK, TENSK, LOAISK, NGAYBD, NGAYKT, MOTA, MANV) VALUES ('SK010', 'Lễ hội ánh sáng', 'Văn hóa', TO_DATE('2025-12-20', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'), 'Trình diễn ánh sáng nghệ thuật và pháo hoa.', 'NV005');
commit;

-- Bảng KHUTROCHOI
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC001', 'Vòng Quay Mặt Trời');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC002', 'Tàu Lượn Siêu Tốc');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC003', 'Nhà Ma');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC004', 'Massage Cá');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC005', 'Công Viên Nước');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC006', 'Rạp Chiếu Phim 9D');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC007', 'Xe Điện Đụng');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC008', 'Lâu Đài Pháp Thuật');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC009', 'Khu Trò Chơi Trẻ Em');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC010', 'Du Thuyền Thiên Nga');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC011', 'Tháp Rơi Tự Do');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC012', 'Đu Dây Mạo Hiểm');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC013', 'Vũ Điệu Tagada');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC014', 'Xe lửa');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC015', 'Bí Mật Rừng Phù Thủy');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC016', 'Khu Chụp Ảnh Kỷ Niệm');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC017', 'Thủy Cung Đại Dương');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC018', 'Khám Phá Vũ Trụ Huyền Bí');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC019', 'Vườn Thú Mini');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC020', 'Lâu Đài Pha Lê');

-- Bảng KHUVUC
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV001', 'Khu hội chợ A', 'Khu vực rộng rãi phù hợp tổ chức hội chợ', 1500000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV002', 'Khu trò chơi nước', 'Khu có hệ thống máng trượt và hồ bơi nhỏ', 2000000, 'Unavailable');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV003', 'Khu tổ chức sự kiện B', 'Phù hợp tổ chức hội nghị ngoài trời', 1800000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV004', 'Gian hàng ăn uống số 1', 'Khu vực đặt các xe bán đồ ăn nhanh', 800000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV005', 'Gian hàng lưu niệm A', 'Chuyên bán đồ lưu niệm, quà tặng', 600000, 'Unavailable');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV006', 'Khu triển lãm ngoài trời', 'Dành cho các hoạt động trưng bày nghệ thuật', 1700000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV007', 'Gian hàng ăn uống số 2', 'Vị trí gần khu trung tâm, đông người qua lại', 950000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV008', 'Khu cắm trại 1', 'Khu có chỗ dựng lều và hệ thống chiếu sáng', 1200000, 'Unavailable');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV009', 'Khu trò chơi thiếu nhi', 'Dành riêng cho trẻ em từ 3 đến 10 tuổi', 1600000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV010', 'Khu hoạt náo tổng hợp', 'Dùng cho biểu diễn văn nghệ, hoạt động cộng đồng', 1900000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV011', 'Gian hàng lưu niệm B', 'Gian hàng góc phải, ít nắng, gần lối ra', 550000, 'Unavailable');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV012', 'Khu vẽ tranh nghệ thuật', 'Khu dành cho trẻ em tô tượng, vẽ tranh cát', 900000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV013', 'Khu tiệc BBQ', 'Có bếp nướng và khu vực ngồi ăn nhóm lớn', 1300000, 'Unavailable');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV014', 'Khu sinh hoạt nhóm', 'Không gian mở cho các buổi sinh hoạt câu lạc bộ', 1100000, 'Available');
INSERT INTO KHUVUC (MAKV, TENKV, MOTA, GIATHUE, TRANGTHAI) VALUES ('KV015', 'Khu trình diễn thời trang', 'Sân khấu nhỏ và đường catwalk sẵn có', 1750000, 'Available');
COMMIT;

-- Bảng VE
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE001', 'Vé Vào Cổng Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 200000, 'KTC001');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE002', 'Vé Vào Cổng Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 120000, 'KTC001');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE003', 'Vé Vòng Quay Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 60000, 'KTC001');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE004', 'Vé Vòng Quay Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC001');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE005', 'Vé Tàu Lượn Siêu Tốc', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 120000, 'KTC002');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE006', 'Vé Nhà Ma Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC003');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE007', 'Vé Nhà Ma Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC003');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE008', 'Vé Massage Cá Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC004');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE009', 'Vé Massage Cá Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC004');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE010', 'Vé Công Viên Nước Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 170000, 'KTC005');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE011', 'Vé Công Viên Nước Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC005');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE012', 'Vé Rạp Chiếu Phim 9D', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC006');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE013', 'Vé Xe Điện Đụng', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC007');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE014', 'Vé Lâu Đài Pháp Thuật Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 80000, 'KTC008');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE015', 'Vé Lâu Đài Pháp Thuật Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 60000, 'KTC008');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE016', 'Vé Khu Trò Chơi Trẻ Em (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC009');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE017', 'Vé Khu Trò Chơi Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC009');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE018', 'Vé Du Thuyền Thiên Nga Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC010');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE019', 'Vé Du Thuyền Thiên Nga Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC010');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE020', 'Vé Tháp Rơi Tự Do', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 130000, 'KTC011');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE021', 'Vé Đu Dây Mạo Hiểm', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 120000, 'KTC012');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE022', 'Vé Vũ Điệu Tagada Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC013');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE023', 'Vé Vũ Điệu Tagada Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC013');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE024', 'Vé Xe Lửa Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 60000, 'KTC014');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE025', 'Vé Xe Lửa Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC014');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE026', 'Vé Bí Mật Rừng Phù Thủy Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC015');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE027', 'Vé Bí Mật Rừng Phù Thủy Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC015');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE028', 'Vé Khu Chụp Ảnh Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC016');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE029', 'Vé Khu Chụp Ảnh Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC016');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE030', 'Vé Thủy Cung Đại Dương Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 140000, 'KTC017');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE031', 'Vé Thủy Cung Đại Dương Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC017');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE032', 'Vé Khám Phá Vũ Trụ Huyền Bí Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC018');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE033', 'Vé Khám Phá Vũ Trụ Huyền Bí Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC018');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE034', 'Vé Vườn Thú Mini Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC019');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE035', 'Vé Vườn Thú Mini Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC019');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE036', 'Vé Lâu Đài Pha Lê Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 80000, 'KTC020');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE037', 'Vé Lâu Đài Pha Lê Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 70000, 'KTC020');


-- Bảng COMBO_VE
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB001_NL', 'Combo Vui Chơi Toàn Cầu (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 630000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB001_TE', 'Combo Vui Chơi Toàn Cầu (Trẻ em)', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 410000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB002', 'Combo Thử Thách Cảm Giác Mạnh', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 540000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB003_NL', 'Combo Gia Đình Vui Vẻ (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 550000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB003_TE', 'Combo Gia Đình Vui Vẻ (Trẻ em)', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 360000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB004', 'Combo Thư Giãn (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 400000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB005_NL', 'Combo Phiêu Lưu Đại Dương (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 560000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB005_TE', 'Combo Phiêu Lưu Đại Dương (Trẻ em)', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 410000);



-- Bảng CHITIET_CB_VE
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE003');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE005');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE010');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE013');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE017');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE002');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE004');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE007');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE011');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE017');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE023');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE003');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE020');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE021');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE018');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE003');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE005');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE010');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE013');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE002');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE004');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE007');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE011');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE017');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB004', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB004', 'VE008');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB004', 'VE016');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB004', 'VE030');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_NL', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_NL', 'VE003');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_NL', 'VE030');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_NL', 'VE032');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_TE', 'VE002');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_TE', 'VE004');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_TE', 'VE031');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_TE', 'VE033');
