
-- Bảng KHUTROCHOI
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC001', 'Vòng Quay Mặt Trời');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC002', 'Tàu Lượn Siêu Tốc');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC003', 'Nhà Ma');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC004', 'Massage Cá');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC005', 'Công Viên Nước');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC006', 'Rạp Chiếu Phim 9D');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC007', 'Xe Điện Đụng');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC008', 'Lâu Đài Pháp Thuật');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC009', 'Khu Trò Chơi Trẻ Em');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC010', 'Du Thuyền Thiên Nga');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC011', 'Tháp Rơi Tự Do');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC012', 'Đu Dây Mạo Hiểm');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC013', 'Vũ Điệu Tagada');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC014', 'Xe lửa');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC015', 'Bí Mật Rừng Phù Thủy');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC016', 'Khu Chụp Ảnh Kỷ Niệm');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC017', 'Thủy Cung Đại Dương');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC018', 'Khám Phá Vũ Trụ Huyền Bí');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC019', 'Vườn Thú Mini');
INSERT INTO KHUTROCHOI (MAKTC, TENKTC) VALUES ('KTC020', 'Lâu Đài Pha Lê');


-- Bảng VE
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE001', 'Vé Vào Cổng Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 200000, 'KTC001');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE002', 'Vé Vào Cổng Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 120000, 'KTC001');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE003', 'Vé Vòng Quay Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 60000, 'KTC001');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE004', 'Vé Vòng Quay Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC001');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE005', 'Vé Tàu Lượn Siêu Tốc', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 120000, 'KTC002');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE006', 'Vé Nhà Ma Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC003');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE007', 'Vé Nhà Ma Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC003');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE008', 'Vé Massage Cá Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC004');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE009', 'Vé Massage Cá Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC004');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE010', 'Vé Công Viên Nước Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 170000, 'KTC005');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE011', 'Vé Công Viên Nước Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC005');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE012', 'Vé Rạp Chiếu Phim 9D', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC006');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE013', 'Vé Xe Điện Đụng', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC007');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE014', 'Vé Lâu Đài Pháp Thuật Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 80000, 'KTC008');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE015', 'Vé Lâu Đài Pháp Thuật Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 60000, 'KTC008');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE016', 'Vé Khu Trò Chơi Trẻ Em (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC009');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE017', 'Vé Khu Trò Chơi Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC009');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE018', 'Vé Du Thuyền Thiên Nga Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC010');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE019', 'Vé Du Thuyền Thiên Nga Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC010');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE020', 'Vé Tháp Rơi Tự Do', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 130000, 'KTC011');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE021', 'Vé Đu Dây Mạo Hiểm', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 120000, 'KTC012');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE022', 'Vé Vũ Điệu Tagada Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC013');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE023', 'Vé Vũ Điệu Tagada Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC013');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE024', 'Vé Xe Lửa Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 60000, 'KTC014');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE025', 'Vé Xe Lửa Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC014');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE026', 'Vé Bí Mật Rừng Phù Thủy Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC015');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE027', 'Vé Bí Mật Rừng Phù Thủy Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 40000, 'KTC015');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE028', 'Vé Khu Chụp Ảnh Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC016');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE029', 'Vé Khu Chụp Ảnh Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 30000, 'KTC016');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE030', 'Vé Thủy Cung Đại Dương Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 140000, 'KTC017');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE031', 'Vé Thủy Cung Đại Dương Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC017');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE032', 'Vé Khám Phá Vũ Trụ Huyền Bí Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC018');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE033', 'Vé Khám Phá Vũ Trụ Huyền Bí Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 100000, 'KTC018');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE034', 'Vé Vườn Thú Mini Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC019');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE035', 'Vé Vườn Thú Mini Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 50000, 'KTC019');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE036', 'Vé Lâu Đài Pha Lê Người Lớn', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 80000, 'KTC020');
INSERT INTO VE (MAVE, TENVE, LOAIVE, HINHANH, GIAVE, MAKTC) VALUES ('VE037', 'Vé Lâu Đài Pha Lê Trẻ Em', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 70000, 'KTC020');


-- Bảng COMBO_VE
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB001_NL', 'Combo Vui Chơi Toàn Cầu (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 630000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB001_TE', 'Combo Vui Chơi Toàn Cầu (Trẻ em)', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 410000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB002', 'Combo Thử Thách Cảm Giác Mạnh', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 540000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB003_NL', 'Combo Gia Đình Vui Vẻ (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 550000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB003_TE', 'Combo Gia Đình Vui Vẻ (Trẻ em)', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 360000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB004', 'Combo Thư Giãn (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 400000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB005_NL', 'Combo Phiêu Lưu Đại Dương (Người lớn)', 'Người lớn', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 560000);
INSERT INTO COMBO_VE (MACB, TENCB, LOAICB, HINHANH, GIACB) VALUES ('CB005_TE', 'Combo Phiêu Lưu Đại Dương (Trẻ em)', 'Trẻ em', 'https://i.postimg.cc/Rh9DnkR1/park.jpg', 410000);



-- Bảng CHITIET_CB_VE
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE003');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE005');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE010');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE013');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_NL', 'VE017');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE002');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE004');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE007');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE011');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE017');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB001_TE', 'VE023');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE003');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE020');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE021');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB002', 'VE018');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE003');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE005');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE010');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_NL', 'VE013');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE002');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE004');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE007');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE011');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB003_TE', 'VE017');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB004', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB004', 'VE008');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB004', 'VE016');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB004', 'VE030');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_NL', 'VE001');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_NL', 'VE003');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_NL', 'VE030');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_NL', 'VE032');

INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_TE', 'VE002');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_TE', 'VE004');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_TE', 'VE031');
INSERT INTO CHITIET_CB_VE (MACB, MAVE) VALUES ('CB005_TE', 'VE033');
