SELECT * FROM TAIKHOAN;
SELECT * FROM KHACHHANG;
SELECT COUNT(*) FROM COMBO_VE;


CREATE USER c##admin_park IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO c##admin_park;
ALTER USER C##admin_park QUOTA UNLIMITED ON USERS;

CREATE TABLE VE (
    MAVE VARCHAR2(10) PRIMARY KEY,
    TENVE VARCHAR2(100) NOT NULL UNIQUE,
    LOAIVE VARCHAR2(50) NOT NULL,
    MOTA VARCHAR2(255),
    HINHANH VARCHAR2(255),
    GIAVE NUMBER(10, 2) NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'Available',
    MAKTC VARCHAR2(10),
    CONSTRAINT FK_VE_KTC FOREIGN KEY (MAKTC) REFERENCES KHUTROCHOI(MAKTC)
);
ALTER TABLE VE ADD CONSTRAINT chk_GIAVE CHECK(GIAVE >= 0);

CREATE TABLE COMBO_VE (
    MACB VARCHAR2(10) PRIMARY KEY,
    TENCB VARCHAR2(100) NOT NULL UNIQUE,
    LOAICB VARCHAR2(50) NOT NULL,
    HINHANH VARCHAR2(255),
    GIACB NUMBER(10, 2) NOT NULL,
    MOTA VARCHAR2(255),
    TRANGTHAI VARCHAR2(20) DEFAULT 'Available'
);
ALTER TABLE COMBO_VE ADD CONSTRAINT chk_GIACB CHECK(GIACB >= 0);

CREATE TABLE CHITIET_CB_VE (
    MACB VARCHAR2(10),
    MAVE VARCHAR2(10),
    PRIMARY KEY (MACB, MAVE),
    CONSTRAINT FK_CB_CB FOREIGN KEY (MACB) REFERENCES COMBO_VE(MACB),
    CONSTRAINT FK_CB_VE FOREIGN KEY (MAVE) REFERENCES VE(MAVE)
);

CREATE TABLE HOADON (
    MAHD VARCHAR2(10) PRIMARY KEY,
    TONGTIENTRUOC NUMBER(12,2),
    TIENGIAMGIA NUMBER(12,2),
    TONGTIENSAU NUMBER(12,2),
    HINHTHUCTT VARCHAR2(50),
    NGAYLAP DATE,
    MAKH VARCHAR2(10),
    MANV VARCHAR2(10),
    MAKM VARCHAR2(10),
    CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HD_KM FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM)
);

CREATE TABLE CHITIET_HD (
    MAHD VARCHAR2(10),
    LOAI VARCHAR2(10), -- 'VE' hoặc 'COMBO'
    MALOAI VARCHAR2(10),
    SOLUONG NUMBER(5),
    THANHTIEN NUMBER(12,2),
    PRIMARY KEY (MAHD, LOAI, MALOAI),
    CONSTRAINT FK_CT_HD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
    -- Không tạo FK trực tiếp cho MALOAI vì phụ thuộc giá trị LOAI
);

CREATE TABLE KHUYENMAI (
    MAKM VARCHAR2(10) PRIMARY KEY,
    TENKM VARCHAR2(100),
    LOAIKM VARCHAR2(20),
    GIATRIGIAM NUMBER(10,2),
    DIEUKIEN VARCHAR2(255),
    NGAYBD DATE,
    NGAYKT DATE,
    TRANGTHAI VARCHAR2(20)
);
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_GIATRIGIAM CHECK(GIATRIGIAM > 0);
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_NGAY CHECK(NGAYKT >= NGAYBD);

CREATE TABLE TAIKHOAN (
    MATK VARCHAR2(20) PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    MATKHAU VARCHAR2(50) NOT NULL,
    LOAITK VARCHAR2(20),
    TRANGTHAI VARCHAR2(20) DEFAULT 'Active'
);
ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_LOAITK CHECK(LOAITK IN('Manager', 'Employee', 'Customer'));
ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_TRANGTHAI CHECK(TRANGTHAI IN('Active', 'Inactive'));

CREATE TABLE KHACHHANG (
    MAKH VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH VARCHAR2(10), 
    SDT VARCHAR2(15) UNIQUE,
    MATK VARCHAR2(10) UNIQUE,
    CONSTRAINT FK_KH_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    NGSINH DATE,
    GIOITINH VARCHAR2(10),
    SDT VARCHAR2(20),
    NGAYVL DATE,
    CHUCVU VARCHAR2(50),
    LUONG NUMBER(12,2),
    MAQL VARCHAR2(10),
    MATK VARCHAR2(10) UNIQUE,
    CONSTRAINT FK_NV_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK),
    CONSTRAINT FK_NV_QL FOREIGN KEY (MAQL) REFERENCES NHANVIEN(MANV)
);
ALTER TABLE NHANVIEN ADD CONSTRAINT chk_LUONG CHECK(LUONG >= 0);

CREATE TABLE CHAMCONG (
    MACHAMCONG VARCHAR2(20) PRIMARY KEY,
    NGAYLV DATE,
    SOGIOLAM NUMBER(5, 2) NOT NULL,
    MANV VARCHAR2(20),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE KHUTROCHOI (
    MAKTC VARCHAR2(10) PRIMARY KEY,
    TENKTC VARCHAR2(100) NOT NULL,
    MOTA VARCHAR2(255),
    TRANGTHAI VARCHAR2(20) DEFAULT 'Available'
);

CREATE TABLE LICH_BAOTRI (
    MABT VARCHAR2(10) PRIMARY KEY, 
    MAKTC VARCHAR2(10) NOT NULL, 
    NGAYBT DATE NOT NULL,                 -- Ngày thực hiện bảo trì
    NGUOIPT VARCHAR2(100),                -- Người thực hiện
    NOIDUNG VARCHAR2(255),                -- Nội dung công việc bảo trì
    CHIPHI NUMBER(12,2),
    TRANGTHAI VARCHAR2(20) DEFAULT 'Đã lên lịch',  -- Trạng thái: Đã lên lịch, Đang thực hiện, Đã hoàn thành, Hủy
    GHICHU VARCHAR2(255),

    CONSTRAINT FK_BAOTRI_KTC FOREIGN KEY (MAKTC) REFERENCES KHUTROCHOI(MAKTC),
    CONSTRAINT FK_BAOTRI_NGUOIPT FOREIGN KEY (NGUOIPT) REFERENCES NHANVIEN(MANV)
);

--CREATE TABLE DICHVU (
--    MADV VARCHAR2(10) PRIMARY KEY,
--    TENDV VARCHAR2(100),
--    MOTA VARCHAR2(255),
--    GIATHUE NUMBER(10,2),
--    SOLUONGCONLAI NUMBER(5)
--);

CREATE TABLE SUKIEN (
    MASK VARCHAR2(10) PRIMARY KEY,
    TENSK VARCHAR2(100),
    LOAISK VARCHAR2(50),
    NGAYBD DATE,
    NGAYKT DATE,
    MOTA VARCHAR2(255),
    MANV VARCHAR2(10),
    CONSTRAINT FK_SK_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE KHUVUC (
    MAKV VARCHAR2(10) PRIMARY KEY,
    TENKV VARCHAR2(100),
    MOTA VARCHAR2(255),
    GIATHUE NUMBER(10,2),
    TRANGTHAI VARCHAR2(20)
);

CREATE TABLE SANPHAM (
    MASP VARCHAR2(10) PRIMARY KEY,
    TENSP VARCHAR2(100),
    LOAISP VARCHAR2(50),
    TONGSL NUMBER(5),
    DONVITINH VARCHAR2(20),
    GIANHAP NUMBER(10,2),
    GHICHU VARCHAR2(255),
    TRANGTHAI VARCHAR2(20)
);

CREATE TABLE PHIEUKHO (
    MAPHIEU VARCHAR2(10) PRIMARY KEY,
    NGAYGIAODICH DATE,
    LOAIPHIEU VARCHAR2(10), -- 'NHAP' hoặc 'XUAT'
    MANV VARCHAR2(10),      -- Người tạo phiếu
    GHICHU VARCHAR2(255),
    CONSTRAINT FK_PK_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE CT_PHIEUKHO (
    MAPHIEU VARCHAR2(10),
    MASP VARCHAR2(10),
    SOLUONG NUMBER(5),
    DONGIA NUMBER(10,2),
    PRIMARY KEY (MAPHIEU, MASP),
    FOREIGN KEY (MAPHIEU) REFERENCES PHIEUKHO(MAPHIEU),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);
