SELECT * FROM TAIKHOAN;
SELECT * FROM KHACHHANG;

CREATE USER c##admin_park IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO c##admin_park;
ALTER USER C##admin_park QUOTA UNLIMITED ON USERS;

CREATE TABLE VE (
    MAVE VARCHAR2(10) PRIMARY KEY,
    TENVE VARCHAR2(100),
    LOAIVE VARCHAR2(50),
    MOTA VARCHAR2(255),
    GIAVE NUMBER(10, 2),
    NGAYSUDUNG DATE,
    TRANGTHAI VARCHAR2(20),
    MAKTC VARCHAR2(10),
    CONSTRAINT FK_VE_KTC FOREIGN KEY (MAKTC) REFERENCES KHUTROCHOI(MAKTC)
);

CREATE TABLE COMBO_VE (
    MACB VARCHAR2(10) PRIMARY KEY,
    TENCB VARCHAR2(100),
    LOAICB VARCHAR2(50),
    GIACB NUMBER(10, 2),
    MOTA VARCHAR2(255)
);

CREATE TABLE CHITIET_CB_VE (
    MACB VARCHAR2(10),
    MAVE VARCHAR2(10),
    PRIMARY KEY (MACB, MAVE),
    CONSTRAINT FK_CB_CB FOREIGN KEY (MACB) REFERENCES COMBO_VE(MACB),
    CONSTRAINT FK_CB_VE FOREIGN KEY (MAVE) REFERENCES VE(MAVE)
);

CREATE TABLE HOADON (
    MAHD VARCHAR2(10) PRIMARY KEY,
    TONGTIENTRUOC NUMBER(12,2),
    TIENGIAMGIA NUMBER(12,2),
    TONGTIENSAU NUMBER(12,2),
    HINHTHUCTT VARCHAR2(50),
    NGAYLAP DATE,
    MAKH VARCHAR2(10),
    MANV VARCHAR2(10),
    MAKM VARCHAR2(10),
    CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HD_KM FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM)
);

CREATE TABLE CHITIET_HD (
    MAHD VARCHAR2(10),
    LOAI VARCHAR2(10), -- 'VE' hoặc 'CB'
    MALOAI VARCHAR2(10),
    SOLUONG NUMBER(5),
    THANHTIEN NUMBER(12,2),
    PRIMARY KEY (MAHD, LOAI, MALOAI),
    CONSTRAINT FK_CT_HD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
    -- Không tạo FK trực tiếp cho MALOAI vì phụ thuộc giá trị LOAI
);

CREATE TABLE KHUYENMAI (
    MAKM VARCHAR2(10) PRIMARY KEY,
    TENKM VARCHAR2(100),
    LOAIKM VARCHAR2(20),
    GIATRIGIAM NUMBER(10,2),
    DIEUKIEN VARCHAR2(255),
    NGAYBD DATE,
    NGAYKT DATE,
    TRANGTHAI VARCHAR2(20)
);
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_GIATRIGIAM CHECK(GIATRIGIAM > 0);
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_LOAIKM CHECK(LOAIKM IN('% discount', 'Fixed discount'));
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_TRANGTHAI_KM CHECK(TRANGTHAI IN('Available', 'Unavailable'));
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_NGAY CHECK(NGAYKT >= NGAYBD);

CREATE TABLE TAIKHOAN (
    MATK VARCHAR2(20) PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    MATKHAU VARCHAR2(50) NOT NULL,
    LOAITK VARCHAR2(20),
    TRANGTHAI VARCHAR2(20) DEFAULT 'Active'
);
ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_LOAITK CHECK(LOAITK IN('Manager', 'Employee', 'Customer'));
ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_TRANGTHAI CHECK(TRANGTHAI IN('Active', 'Inactive'));

CREATE TABLE KHACHHANG (
    MAKH VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH VARCHAR2(10), 
    SDT VARCHAR2(15) UNIQUE,
    MATK VARCHAR2(10) UNIQUE,
    CONSTRAINT FK_KH_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);
--ALTER TABLE KHACHHANG ADD CONSTRAINT chk_NGAYSINH CHECK(NGAYSINH < SYSDATE);
ALTER TABLE KHACHHANG ADD CONSTRAINT chk_GIOITINH CHECK(GIOITINH IN('Male', 'Female', 'None'));

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    NGSINH DATE,
    GIOITINH VARCHAR2(10),
    SDT VARCHAR2(20),
    NGAYVL DATE,
    CHUCVU VARCHAR2(50),
    LUONG NUMBER(12,2),
    MAQL VARCHAR2(10),
    MATK VARCHAR2(10) UNIQUE,
    CONSTRAINT FK_NV_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK),
    CONSTRAINT FK_NV_QL FOREIGN KEY (MAQL) REFERENCES NHANVIEN(MANV)
);
ALTER TABLE NHANVIEN ADD CONSTRAINT chk_GIOITINH_NV CHECK(GIOITINH IN('Male', 'Female', 'None'));
ALTER TABLE NHANVIEN ADD CONSTRAINT chk_LUONG CHECK(LUONG >= 0);

CREATE TABLE KHUTROCHOI (
    MAKTC VARCHAR2(10) PRIMARY KEY,
    TENKTC VARCHAR2(100),
    MOTA VARCHAR2(255),
    TRANGTHAI VARCHAR2(20)
);

CREATE TABLE DICHVU (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(100),
    MOTA VARCHAR2(255),
    GIATHUE NUMBER(10,2),
    SOLUONGCONLAI NUMBER(5)
);

CREATE TABLE SUKIEN (
    MASK VARCHAR2(10) PRIMARY KEY,
    TENSK VARCHAR2(100),
    LOAISK VARCHAR2(50),
    NGAYBD DATE,
    NGAYKT DATE,
    MOTA VARCHAR2(255),
    MANV VARCHAR2(10),
    CONSTRAINT FK_SK_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

--CREATE TABLE KHUVUC (
--    MAKV VARCHAR2(10) PRIMARY KEY,
--    TENKV VARCHAR2(100),
--    MOTA VARCHAR2(255),
--    GIATHUE NUMBER(10,2),
--    TRANGTHAI VARCHAR2(20)
--);

CREATE TABLE SANPHAM (
    MASP VARCHAR2(10) PRIMARY KEY,
    TENSP VARCHAR2(100),
    LOAISP VARCHAR2(50),
    TONGSL NUMBER(5),
    DONVITINH VARCHAR2(20),
    TRANGTHAI VARCHAR2(20),
    NHACC VARCHAR2(100),
    GIANHAP NUMBER(10,2),
    GHICHU VARCHAR2(255)
);
