// Bảng Tài khoản
CREATE SEQUENCE seq_taikhoan START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_taikhoan_pk
BEFORE INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    SELECT seq_taikhoan.NEXTVAL INTO :NEW.MATK FROM dual;
END;

// Bảng Khách hàng 
CREATE SEQUENCE seq_khachhang START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_khachhang_pk
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    SELECT seq_khachhang.NEXTVAL INTO :NEW.MAKH FROM dual;
END;